# Generated by Django 5.1.5 on 2025-03-01 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(help_text="Введите тему письма", max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "letter",
                    models.CharField(
                        help_text="Введите содержание письма", max_length=10000, verbose_name="Содержание письма"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.CharField(help_text="Введите e-mail получателя", max_length=100, verbose_name="E-mail"),
                ),
                ("name", models.CharField(help_text="Введите ФИО получателя", max_length=100, verbose_name="ФИО")),
                (
                    "comment",
                    models.CharField(help_text="Введите комментарий", max_length=500, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата первой отправки")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("завершена", "Завершена"), ("создана", "Создана"), ("запущена", "Запущена")],
                        help_text="Выберите статус рассылки",
                        max_length=100,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите сообщение для рассылки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailing_app.letter",
                        verbose_name="Сообщение",
                    ),
                ),
                ("recipient_list", models.ManyToManyField(to="mailing_app.recipient")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")], max_length=20),
                ),
                ("response", models.TextField()),
                ("mailing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing_app.mailing")),
            ],
        ),
    ]
